[2025-08-03T15:14:31.441+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T15:12:14+00:00 [queued]>
[2025-08-03T15:14:31.444+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T15:12:14+00:00 [queued]>
[2025-08-03T15:14:31.444+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2025-08-03T15:14:31.449+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): initialize_rl_environment> on 2025-08-03 15:12:14+00:00
[2025-08-03T15:14:31.451+0000] {standard_task_runner.py:60} INFO - Started process 1101 to run task
[2025-08-03T15:14:31.454+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dit_uq_stage2', 'initialize_rl_environment', 'manual__2025-08-03T15:12:14+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dit_uq_stage2.py', '--cfg-path', '/tmp/tmplurfz4ic']
[2025-08-03T15:14:31.454+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask initialize_rl_environment
[2025-08-03T15:14:31.472+0000] {task_command.py:423} INFO - Running <TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T15:12:14+00:00 [running]> on host 526a1360f1e8
[2025-08-03T15:14:31.496+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'initialize_rl_environment', field 'environment'. Template: {'AIRFLOW_CTX_DAG_RUN_ID': '{{{{ run_id }}}}', 'CUDA_VISIBLE_DEVICES': '0'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
[2025-08-03T15:14:31.498+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
[2025-08-03T15:14:31.504+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dit_uq_stage2, task_id=initialize_rl_environment, execution_date=20250803T151214, start_date=20250803T151431, end_date=20250803T151431
[2025-08-03T15:14:31.507+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 22 for task initialize_rl_environment (expected token ':', got '}'; 1101)
[2025-08-03T15:14:31.511+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T15:14:31.520+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
