[2025-08-03T01:57:30.321+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T01:46:49+00:00 [queued]>
[2025-08-03T01:57:30.323+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T01:46:49+00:00 [queued]>
[2025-08-03T01:57:30.323+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-08-03T01:57:30.327+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): initialize_rl_environment> on 2025-08-03 01:46:49+00:00
[2025-08-03T01:57:30.329+0000] {standard_task_runner.py:60} INFO - Started process 582 to run task
[2025-08-03T01:57:30.330+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dit_uq_stage2', 'initialize_rl_environment', 'manual__2025-08-03T01:46:49+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dit_uq_stage2.py', '--cfg-path', '/tmp/tmpb1ecet26']
[2025-08-03T01:57:30.331+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask initialize_rl_environment
[2025-08-03T01:57:30.346+0000] {task_command.py:423} INFO - Running <TaskInstance: dit_uq_stage2.initialize_rl_environment manual__2025-08-03T01:46:49+00:00 [running]> on host 526a1360f1e8
[2025-08-03T01:57:30.366+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='molecule-ai-team' AIRFLOW_CTX_DAG_ID='dit_uq_stage2' AIRFLOW_CTX_TASK_ID='initialize_rl_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T01:46:49+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-03T01:46:49+00:00'
[2025-08-03T01:57:30.367+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 428, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dit_uq_stage2.py", line 63, in initialize_rl_environment
    from src.rl.samplers import PreferenceSampler
ModuleNotFoundError: No module named 'src'
[2025-08-03T01:57:30.370+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dit_uq_stage2, task_id=initialize_rl_environment, execution_date=20250803T014649, start_date=20250803T015730, end_date=20250803T015730
[2025-08-03T01:57:30.372+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task initialize_rl_environment (No module named 'src'; 582)
[2025-08-03T01:57:30.388+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-03T01:57:30.395+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
